### ISSUE TITLE
Addition to directory

### ISSUE THREAD

**Issue by Pinpas** [fishttp/awesome-bluesky#29]
https://bluesky-thread-composer.pages.dev/

not sure what category tho.

Wanted to make a Thread on Bluesky, but was way too hard to make it look good.

- Local Stored Data 
- Thread Preview 
- Simple Edits 
- 2/3x Faster than bluesky "thread" maker 

Let me know what you think.

I've made it myself if you have any questions check my bluesky:
@hugotions.bsky.social‬

**Comment by fishttp** [comment]
thanks, added
