### ISSUE TITLE
Add Bluesky-sync for syncing starter packs and lists from code

### ISSUE THREAD

**Issue by patcon** [fishttp/awesome-bluesky#31]
https://github.com/jaseemabid/bluesky-sync

Not generalized yet, but very simple and interesting project :) I'd like to have it sync from remote CSV soon(ie google sheets)

cc @jaseemabid

**Comment by fishttp** [comment]
looks interesting but probably too complicated for the very newbie friendly audience this list is targeting

**Comment by patcon** [comment]
Ok thanks, will make contributions to another awesome list then
